/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Views;

/**
 *
 * @author erosi
 */
public class CambioUserN extends javax.swing.JFrame {

    /** Creates new form CambioUserN */
    public CambioUserN() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblUActual = new javax.swing.JLabel();
        tfRespuesta = new javax.swing.JTextField();
        lblUnuevo = new javax.swing.JLabel();
        tfRespuesta1 = new javax.swing.JTextField();
        lblUConfirmar = new javax.swing.JLabel();
        tfRespuesta2 = new javax.swing.JTextField();
        bValidar = new javax.swing.JButton();
        Bback = new javax.swing.JButton();
        Blogin = new javax.swing.JButton();
        lblAlert = new javax.swing.JLabel();
        lblMensaje = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Cambio UserName");

        lblUActual.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblUActual.setForeground(new java.awt.Color(255, 255, 255));
        lblUActual.setText("Usename Actual");
        lblUActual.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblUnuevo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblUnuevo.setForeground(new java.awt.Color(255, 255, 255));
        lblUnuevo.setText("Nuevo UserName");
        lblUnuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblUConfirmar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblUConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        lblUConfirmar.setText("Confirme UserName");
        lblUConfirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        bValidar.setBackground(new java.awt.Color(0, 0, 0));
        bValidar.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        bValidar.setForeground(new java.awt.Color(255, 255, 255));
        bValidar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Inicio de sesion.png"))); // NOI18N
        bValidar.setText("Validar");
        bValidar.setBorderPainted(false);
        bValidar.setContentAreaFilled(false);
        bValidar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bValidar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Inicio de sesion.png"))); // NOI18N
        bValidar.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        bValidar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bValidar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bValidarMouseClicked(evt);
            }
        });
        bValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bValidarActionPerformed(evt);
            }
        });

        Bback.setBackground(new java.awt.Color(0, 0, 0));
        Bback.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        Bback.setForeground(new java.awt.Color(255, 255, 255));
        Bback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/salida.png"))); // NOI18N
        Bback.setText("Volver");
        Bback.setBorderPainted(false);
        Bback.setContentAreaFilled(false);
        Bback.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Bback.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/salida (1).png"))); // NOI18N
        Bback.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Bback.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Bback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BbackMouseClicked(evt);
            }
        });
        Bback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbackActionPerformed(evt);
            }
        });

        Blogin.setBackground(new java.awt.Color(0, 0, 0));
        Blogin.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        Blogin.setForeground(new java.awt.Color(255, 255, 255));
        Blogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iniciar-sesion.png"))); // NOI18N
        Blogin.setText("login");
        Blogin.setBorderPainted(false);
        Blogin.setContentAreaFilled(false);
        Blogin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Blogin.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iniciar-sesionSelected.png"))); // NOI18N
        Blogin.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Blogin.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Blogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BloginMouseClicked(evt);
            }
        });
        Blogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloginActionPerformed(evt);
            }
        });

        lblAlert.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblAlert.setForeground(new java.awt.Color(0, 255, 255));
        lblAlert.setText("ZONA DE MENSAJES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(lblTitulo)
                .addContainerGap(211, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Bback)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblAlert)
                        .addGap(45, 45, 45)))
                .addGap(71, 71, 71)
                .addComponent(Blogin)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUnuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfRespuesta2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfRespuesta)
                    .addComponent(tfRespuesta1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(123, 123, 123))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bValidar)
                .addGap(244, 244, 244))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUnuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfRespuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblUConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfRespuesta2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bValidar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblAlert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Bback, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Blogin, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bValidarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bValidarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bValidarMouseClicked

    private void bValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bValidarActionPerformed

    }//GEN-LAST:event_bValidarActionPerformed

    private void BbackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BbackMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BbackMouseClicked

    private void BbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbackActionPerformed
        Inicio ini = new Inicio();
        ini.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BbackActionPerformed

    private void BloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BloginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BloginMouseClicked

    private void BloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloginActionPerformed
        IniciarSesion is =new IniciarSesion();
        is.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BloginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CambioUserN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CambioUserN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CambioUserN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CambioUserN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CambioUserN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bback;
    private javax.swing.JButton Blogin;
    private javax.swing.JButton bValidar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAlert;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUActual;
    private javax.swing.JLabel lblUConfirmar;
    private javax.swing.JLabel lblUnuevo;
    private javax.swing.JTextField tfRespuesta;
    private javax.swing.JTextField tfRespuesta1;
    private javax.swing.JTextField tfRespuesta2;
    // End of variables declaration//GEN-END:variables

}
