/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Models.Comisario;
import Models.ComisarioADO;
import Models.TryParse;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ab
 */
public class GestionUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form Comisario
     */
    ResultSet rs;
    public GestionUsuarios() {
        initComponents();
    }
    public void Habilitar(){
           this.txt_Run.setEnabled(true);
           this.txt_Nombre.setEnabled(true);
           this.txt_Appat.setEnabled(true); 
           this.txt_Apmat.setEnabled(true);
           this.txt_Direccion.setEnabled(true);
           this.txt_Tel.setEnabled(true);
           this.txt_Email.setEnabled(true);
           this.CBtc.setEnabled(true);
     }
    public void Deshabilitar(){
           this.txt_Run.setEnabled(false);
           this.txt_Nombre.setEnabled(false);
           this.txt_Appat.setEnabled(false); 
           this.txt_Apmat.setEnabled(false);
           this.txt_Direccion.setEnabled(false);
           this.txt_Tel.setEnabled(false);
           this.txt_Email.setEnabled(false);
           this.CBtc.setEnabled(false);
     }
     public void limpiar(){
           this.txt_Run.setText("");
           this.txt_ID.setText("");
           this.txt_Nombre.setText("");
           this.txt_Appat.setText(""); 
           this.txt_Apmat.setText("");
           this.txt_Direccion.setText("");
           this.txt_Tel.setText("");
           this.txt_Email.setText("");
           this.CBtc.setSelectedIndex(0);
 }
    private void cargarRegistros(){
      DefaultTableModel modelo = (DefaultTableModel) table.getModel();
      modelo.setRowCount(0);
      ComisarioADO em= new ComisarioADO();
      rs = em.Consulta("Select * from Cliente");
      try{
          while(rs.next()){
          Vector op= new Vector();
          op.add(rs.getInt(1));
          op.add(rs.getInt(2));
          op.add(rs.getString(3));
          op.add(rs.getString(4));
          op.add(rs.getString(5));
          op.add(rs.getString(6));
          op.add(rs.getBoolean(7));
          op.add(rs.getString(8));
          op.add(rs.getString(9));
          op.add(rs.getString(10));
          modelo.addRow(op);
          table.setModel(modelo);
          }
      }catch(SQLException e){
      }
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_Nombre = new javax.swing.JTextField();
        txt_Appat = new javax.swing.JTextField();
        CBtc = new javax.swing.JComboBox();
        txt_Run = new javax.swing.JTextField();
        txt_Tel = new javax.swing.JTextField();
        txt_Apmat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_Email = new javax.swing.JTextField();
        txt_Direccion = new javax.swing.JTextField();
        txt_ID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        rHombre = new javax.swing.JRadioButton();
        rMujer = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        b_agregar = new javax.swing.JButton();
        b_modificar = new javax.swing.JButton();
        b_eliminar = new javax.swing.JButton();
        b_restablecer = new javax.swing.JButton();
        b_salir = new javax.swing.JButton();
        b_consultaporid = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        lblRespuesta = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tBuscar = new javax.swing.JTextField();
        b_buscar = new javax.swing.JButton();
        txt_mensajes = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N

        jLabel1.setText("ID :");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Apellido mat. :");

        jLabel4.setText("Tipo Usuario :");

        jLabel5.setText("Run :");

        jLabel6.setText("Telefono :");

        jLabel7.setText("E_mail :");

        txt_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_NombreKeyTyped(evt);
            }
        });

        txt_Appat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_AppatKeyTyped(evt);
            }
        });

        CBtc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione...", "Comisario", "Juez", "Deportista", " " }));
        CBtc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBtcActionPerformed(evt);
            }
        });

        txt_Run.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_RunKeyTyped(evt);
            }
        });

        txt_Tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_TelKeyTyped(evt);
            }
        });

        txt_Apmat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_ApmatKeyTyped(evt);
            }
        });

        jLabel8.setText("Apellido pat. :");

        jLabel9.setText("Direccion :");

        jLabel10.setText("Sexo :");

        rHombre.setText("Hombre");

        rMujer.setText("Mujer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txt_Apmat, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txt_Appat, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(231, 231, 231))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_Run, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                                        .addComponent(jLabel9))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel10))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Tel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rHombre, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rMujer, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(CBtc, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(rHombre)
                    .addComponent(rMujer))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_Run, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_Tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_Appat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Apmat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(CBtc, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        b_agregar.setText("Agregar");
        b_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_agregarBotonAgregar(evt);
            }
        });

        b_modificar.setText("Modificar");
        b_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_modificarActionPerformed(evt);
            }
        });

        b_eliminar.setText("Eliminar");
        b_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_eliminarActionPerformed(evt);
            }
        });

        b_restablecer.setText("Restablecer");
        b_restablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_restablecerActionPerformed(evt);
            }
        });

        b_salir.setText("Salir");
        b_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_salirActionPerformed(evt);
            }
        });

        b_consultaporid.setText("Traer datos por id");
        b_consultaporid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_consultaporidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_eliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_restablecer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_consultaporid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(b_agregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b_consultaporid)
                .addGap(18, 18, 18)
                .addComponent(b_modificar)
                .addGap(18, 18, 18)
                .addComponent(b_eliminar)
                .addGap(18, 18, 18)
                .addComponent(b_restablecer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(b_salir)
                .addGap(7, 7, 7))
        );

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tipo Usuario", "Run", "Nombre", "Apellido pat.", "Apellido mat.", "Sexo ", "Direccion", "Telefono", "Email"
            }
        ));
        jScrollPane1.setViewportView(table);

        jLabel11.setText("Buscar por:");

        tBuscar.setText("Filtro");
        tBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tBuscarFocusGained(evt);
            }
        });
        tBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBuscarActionPerformed(evt);
            }
        });

        b_buscar.setText("Buscar");
        b_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_buscarActionPerformed(evt);
            }
        });

        txt_mensajes.setForeground(new java.awt.Color(255, 51, 51));
        txt_mensajes.setText("Zona de Mensajes");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Gestion de Usuarios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRespuesta))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_mensajes)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(b_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(252, 252, 252))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(471, 471, 471)
                        .addComponent(lblRespuesta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(tBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(b_buscar)))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(txt_mensajes)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_NombreKeyTyped

    }//GEN-LAST:event_txt_NombreKeyTyped

    private void txt_AppatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_AppatKeyTyped

    }//GEN-LAST:event_txt_AppatKeyTyped

    private void CBtcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBtcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBtcActionPerformed

    private void txt_RunKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_RunKeyTyped

    }//GEN-LAST:event_txt_RunKeyTyped

    private void txt_TelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TelKeyTyped

    }//GEN-LAST:event_txt_TelKeyTyped

    private void txt_ApmatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ApmatKeyTyped

    }//GEN-LAST:event_txt_ApmatKeyTyped
    private String validarEntero(String valor,String nombreVariable){
    if("".equals(valor)){
        return "Debe ingresar "+ nombreVariable;
    }else{
        TryParse tr= new TryParse();
        if(tr.esEntero(valor)){
            int valorEntero= Integer.valueOf(valor);
            if(valorEntero > 0){
               return "";
            }else{
                return "Dbe ingresar "+ nombreVariable+" >0";
            }
        }else{
                return "Debe ingresar "+nombreVariable+" numerico entero";
            }
        }
    }
    private String validarFloat(String valor,String nombreVariable){
    if("".equals(valor)){
        return "Debe ingresar "+ nombreVariable;
    }else{
        TryParse tr= new TryParse();
        if(tr.esFloat(valor)){
            float valorReal= Float.valueOf(valor);
            if(valorReal > 0){
               return "";
            }else{
                return "Dbe ingresar "+ nombreVariable+" >0";
            }
        }else{
                return "Debe ingresar "+nombreVariable+" numerico Real";
            }
        }
    }
    private void b_agregarBotonAgregar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_agregarBotonAgregar
    
   //  lblRespuesta.setText(validarEntero(tCodigo.getText(),"Id cliente"));
   //     if("".equals(lblRespuesta.getText())){
   //         if("".equals(tRun.getText())){
   //             lblRespuesta.setText("Debe ingresar un run");
   //             tRun.requestFocus();
   //         }else{
   //             if("".equals(tNombre.getText())){
   //                 lblRespuesta.setText("Debe ingresar un nombre");
   //                 tNombre.requestFocus();
   //             }else{
   //                 if("".equals(tAppat.getText())){
   //                     lblRespuesta.setText("Debe Ingresar su apellido paterno");
   //                     tAppat.requestFocus();
   //                 }else{
   //                     if("".equals(tApmat.getText())){
   //                         lblRespuesta.setText("Debe ingresar su apellido materno");
   //                         tApmat.requestFocus();
   //                     }else{
   //                         if("".equals(tDireccion.getText())){
   //                             lblRespuesta.setText("Debe ingresar una direccion");
   //                             tDireccion.requestFocus();
    //                        }else{
   //                             if("".equals(tTel.getText())){
    //                                lblRespuesta.setText("Debe ingresar un numero de telefono");
    //                                tTel.requestFocus();
    //                            }else{
    //                                if("".equals(tEmail.getText())){
    //                                    lblRespuesta.setText("Debe de ingresar un email");
    //                                    tEmail.requestFocus();
    //                                }else{
    //                                    if(CBtc.getSelectedIndex()==0){
    //                                        lblRespuesta.setText("Debe de seleccionar una opcion");
    //                                        CBtc.requestFocus();
    //                                    }else{
    //                                        int codigo = Integer.valueOf(tCodigo.getText());
                                           // ControladorComisario cli= new ControladorComisario();
                                           // lblRespuesta.setText(cli.existeCliente(codigo));
                                          //  if("".equals(lblRespuesta.getText())){
                                          //      cli.agregarCliente(codigo,CBtc.getSelectedIndex(),tRun.getText(),tNombre.getText(),tAppat.getText(),tApmat.getText(),tDireccion.getText(),tTel.getText(),tEmail.getText());///FALTA SEXO USUARIO
                                          //      lblRespuesta.setText("Cliente ha sido guardado");
                                         //       limpiar();
                                         //       tCodigo.requestFocus();
                                         //       cargarRegistros();

                                         //   }else{
                                         //       if(!"".equals(lblRespuesta.getText())){
                                         //           lblRespuesta.setText("Id existente");
                                        //        }
                                      //      }
                                    //    }
                                  //  }
                            //    }
                        //    }
                    //    }
                //    }
            //    }
          //  }
      //  }else{
      //      tCodigo.requestFocus();
      //  }
    }//GEN-LAST:event_b_agregarBotonAgregar

    private void b_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_modificarActionPerformed
        lblRespuesta.setText(validarEntero(txt_ID.getText(),"Id cliente"));
        if("".equals(lblRespuesta.getText())){
            if("".equals(txt_Run.getText())){
                lblRespuesta.setText("Debe ingresar un run");
                txt_Run.requestFocus();
            }else{
                if("".equals(txt_Nombre.getText())){
                    lblRespuesta.setText("Debe ingresar un nombre.");
                    txt_Nombre.requestFocus();
                }else{
                    if("".equals(txt_Appat.getText())){
                        lblRespuesta.setText("Debe ingresar el apellido Paterno.");
                        txt_Appat.requestFocus();
                    }else{
                        if("".equals(txt_Apmat.getText())){
                            lblRespuesta.setText("Debe ingresar un apellido Materno.");
                            txt_Apmat.requestFocus();
                        }else{
                            if("".equals(txt_Tel.getText())){
                                lblRespuesta.setText("Debe ingresar un numero.");
                                txt_Tel.requestFocus();
                            }else{
                                if("".equals(txt_Email.getText())){
                                    lblRespuesta.setText("Debe ingresar email.");
                                    txt_Email.requestFocus();
                                }else{
                                    int codigo = Integer.valueOf(txt_ID.getText());
                                   // ControladorComisario cli= new ControladorComisario();
                                   // lblRespuesta.setText(cli.existeCliente(codigo));
                                   // if(!"".equals(lblRespuesta.getText())){
                                   //     cli.actualizarCliente(codigo, CBtc.getSelectedIndex(),tRun.getText(),tNombre.getText(), tAppat.getText(),tApmat.getText(),tDireccion.getText(), tTel.getText(),tEmail.getText());///FALTA EL SEXO CLIENTE
                                    //    lblRespuesta.setText("Cliente ha sido actualizado");
                                    //    limpiar();
                                    //    tCodigo.requestFocus();
                                    //    cargarRegistros();
                                  //  }else{
                                 //       if("".equals(lblRespuesta.getText())){
                                 //           lblRespuesta.setText("Id no existente en la BD");
                                 //           tCodigo.requestFocus();
                               //         }
                              //      }
                                }
                            }
                        }
                    }
                }
            }
        }else{
            txt_ID.requestFocus();
        }
    }//GEN-LAST:event_b_modificarActionPerformed

    private void b_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_eliminarActionPerformed
  //      lblRespuesta.setText(validarEntero(tCodigo.getText(),"Id cliente"));
  //      if("".equals(lblRespuesta.getText())){
  //          int codigo= Integer.valueOf(tCodigo.getText());
  //          ControladorComisario cli= new ControladorComisario();
  //          lblRespuesta.setText(cli.eliminarCliente(codigo));
  //          if("".equals(lblRespuesta.getText())){
  //              lblRespuesta.setText("Los datos del cliente se han eliminado");
   //             tCodigo.setText("");
   //             tCodigo.requestFocus();
   //         }else{
     //           lblRespuesta.setText("Los datos no se han podido eliminar, reintente");
       //         tCodigo.requestFocus();
         //       tCodigo.selectAll();
     //       }
     //   }else{
     //       tCodigo.requestFocus();
     //   }
    }//GEN-LAST:event_b_eliminarActionPerformed

    private void b_restablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_restablecerActionPerformed
        limpiar();
        cargarRegistros();
    }//GEN-LAST:event_b_restablecerActionPerformed

    private void b_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_salirActionPerformed

        Menu a= new Menu();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_b_salirActionPerformed

    private void b_consultaporidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_consultaporidActionPerformed
       // lblRespuesta.setText(validarEntero(tCodigo.getText(),"Id Cliete"));
       // if("".equals(lblRespuesta.getText())){
       //     int codigo=Integer.valueOf(tCodigo.getText());
       //     ControladorComisario cli= new ControladorComisario();
       //     lblRespuesta.setText(cli.existeCliente(codigo));
       //     if("".equals(lblRespuesta.getText())){
       //         lblRespuesta.setText("El id no se encuaenta en la BD");
       //         tCodigo.requestFocus();
       //     }else{
       //         String mensaje= lblRespuesta.getText();
       //         if(mensaje.indexOf("existe")==-1){
       //             lblRespuesta.setText("Id cleinte no fue consultado, reintente");
       //             tCodigo.requestFocus();
       //             Habilitar();
       //         }else{
       //             lblRespuesta.setText(cli.consultaxDatosUnCliente(codigo));
                 //   if("".equals(lblRespuesta.getText())){
                  //      Cliente cli = new Cliente();
                 //       cl= cli.obtenerDatosCliente();
                 //       CBtc.setSelectedIndex(cl.getTipoCliente());
                 //       tRun.setText(cl.getRun());
                 //       tNombre.setText(cl.getNombre());
                 //       tAppat.setText(cl.getAppat());
                 //       tApmat.setText(cl.getApmat());
                 //       if(cl.getSexoC()==false){
                 //           rHombre.setSelected(true);
                 //       }else{
                 //           rMujer.setSelected(true);
                 //       }
                 //       tDireccion.setText(cl.getDireccion());
                 //       tTel.setText(cl.getTel());
                 //       tEmail.setText(cl.getEmail());
                 //       Bmodificar.setEnabled(true);
                 //       Beliminar.setEnabled(true);
                 //       Habilitar();
    //                }
    //            }
    //        }
    //    }
    }//GEN-LAST:event_b_consultaporidActionPerformed

    private void tBuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tBuscarFocusGained
        tBuscar.setText("");
    }//GEN-LAST:event_tBuscarFocusGained

    private void tBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBuscarActionPerformed
        tBuscar.selectAll();
    }//GEN-LAST:event_tBuscarActionPerformed

    private void b_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_buscarActionPerformed

       // while(table.getRowCount()!= 0){
       //     ((DefaultTableModel) table.getModel()).removeRow(0);
       // }
       // if("".equals(tBuscar.getText())){
       //     tBuscar.setText("Debe ingresar un filtro a consultar. ");

       // }else{
       //     ControladorComisario ocp = new ControladorComisario();
       //     String mensaje = ocp.consultaxDatosUnClienteFiltrados(tBuscar.getText());
       //     if("".equals(mensaje)){ // Hay datos en base al Filtro
       //         DefaultTableModel modelo = (DefaultTableModel) table.getModel();
       //         Object [] fila = new Object[10];
       //         ArrayList<Comisario> listaClientes;
       //         listaClientes = ocp.obtenerDatosClienteFiltrados();
       //         for(Comisario e : listaClientes){
       //             fila[0] = e.getIdCom();
       //             fila[1] = e.getRunCom();
       //             fila[2] = e.getNombreCom();
       //             fila[3] = e.getAppatCom();
       //             fila[4] = e.getApmatCom();
       //             fila[5] = e.getFonoCom();
       //             fila[6] = e.getEmailCom();
        //            modelo.addRow(fila);
        //        }
       //     }else{
       //         tBuscar.setText(mensaje);
       //     }

       // }
       // tBuscar.selectAll();
       // tBuscar.requestFocus();
    }//GEN-LAST:event_b_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CBtc;
    private javax.swing.JButton b_agregar;
    private javax.swing.JButton b_buscar;
    private javax.swing.JButton b_consultaporid;
    private javax.swing.JButton b_eliminar;
    private javax.swing.JButton b_modificar;
    private javax.swing.JButton b_restablecer;
    private javax.swing.JButton b_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRespuesta;
    private javax.swing.JRadioButton rHombre;
    private javax.swing.JRadioButton rMujer;
    private javax.swing.JTextField tBuscar;
    private javax.swing.JTable table;
    private javax.swing.JTextField txt_Apmat;
    private javax.swing.JTextField txt_Appat;
    private javax.swing.JTextField txt_Direccion;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JTextField txt_Run;
    private javax.swing.JTextField txt_Tel;
    private javax.swing.JLabel txt_mensajes;
    // End of variables declaration//GEN-END:variables
}
